### ISSUE TITLE
AttributeError: module 'gd.memory' has no attribute 'get_memory'

### ISSUE THREAD

**Issue by 9alexv7** [FigmentBoy/GD-AI#4]
![image](https://user-images.githubusercontent.com/87235409/188275012-3124fb67-683c-43be-98cb-9931cd9a2242.png)

**Comment by TechStudent10** [comment]
Same error here.

**Comment by V0id3174** [comment]
I also get this, how do I fix it?

**Comment by WoolEndy** [comment]
Install ‘gd.py’ with ‘pip install gd.py’.

**Comment by Exernited** [comment]
this command doesnt work and even if you install gd.py this shows up
![image](https://user-images.githubusercontent.com/112814560/236692417-6054ec62-c0a7-48fa-96d9-0b8bc2657de5.png)

**Comment by WoolEndy** [comment]
Uninstall any other gd modules.

**Comment by Exernited** [comment]
didnt have any installed except gd.py

**Comment by Exernited** [comment]
okay I fixed it but know im stuck on gen 1 and when I enter a level it shows this
![image](https://user-images.githubusercontent.com/112814560/236693498-aefc78f4-6b44-4811-9bfe-85024e6d615b.png)

**Comment by Exernited** [comment]
Okay it works

**Comment by XCATsus** [comment]
> Uninstall any other gd modules.

How do I do that?

**Comment by TechStudent10** [comment]
> Okay it works

How?

**Comment by WoolEndy** [comment]
> > Uninstall any other gd modules.
> 
> How do I do that?

```python
pip list
```
and then

```python 
pip uninstall <package name>
```

**Comment by Exernited** [comment]
> > Okay it works
> 
> How?

I can send you my folder if you want

**Comment by Heatwave3** [comment]
can anyone please help? it says

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ranch\Downloads\GD-AI-master\__main__.py", line 10, in <module>
    mem = gd.memory.get_memory()
          ^^^^^^^^^
AttributeError: module 'gd' has no attribute 'memory'

**Comment by WoolEndy** [comment]
Install the “gd.py” module and uninstall any other you installed.

**Comment by Heatwave3** [comment]
tried that but it doesnt work?

**Comment by Heatwave3** [comment]
it worked but its stuck on gen 1

**Comment by WoolEndy** [comment]
Go to the level first and then open the bot.

**Comment by Heatwave3** [comment]
like enter the level first or leave it on the title of the level?

**Comment by Heatwave3** [comment]
it just says 

C:\Users\ranch\Downloads\GD-AI-master>py .
GEN 1

and its been stuck like that

**Comment by Heatwave3** [comment]
thanks! i fixed it it works perfectly now!

**Comment by firewyrmgd** [comment]
it keeps saying that py is not a internal or external command

**Comment by WoolEndy** [comment]
Install Python.

**Comment by firewyrmgd** [comment]
it says this now:
ERROR: Could not find a version that satisfies the requirement python (from versions: none)
ERROR: No matching distribution found for python

**Comment by WoolEndy** [comment]
Try doing "winget install Python.Python.3.11" in Command Prompt.

**Comment by firewyrmgd** [comment]
now whenever i use the command py, it switches to a different format and doesn't activate the hack.

**Comment by firewyrmgd** [comment]
and now when i say py ., it says:
C:\Users\(my name here)\AppData\Local\Programs\Python\Python311\python.exe: can't find '__main__' module in 'C:\\Users\\(my name here)'

**Comment by firewyrmgd** [comment]
now i'm getting the gd.memory has no attribute get_memory thing, but I don't have any othe gd stuff active, so how do i fix it?

**Comment by Exernited** [comment]
> now i'm getting the gd.memory has no attribute get_memory thing, but I don't have any othe gd stuff active, so how do i fix it?

I can send you my folder

**Comment by THESHARK9001** [comment]
> didnt have any installed except gd.py

How did you fix this? I am getting the same error that others had

**Comment by THESHARK9001** [comment]
> Okay it works

How?

**Comment by NumbersTada** [comment]
> okay I fixed it but know im stuck on gen 1 and when I enter a level it shows this ![image](https://user-images.githubusercontent.com/112814560/236693498-aefc78f4-6b44-4811-9bfe-85024e6d615b.png)

how did you fix this
