### ISSUE TITLE
ModuleNotFoundError: No module named 'win32gui'

### ISSUE THREAD

**Issue by XCATsus** [FigmentBoy/GD-AI#7]
I keep getting this error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Admin\Documents\gdai\__main__.py", line 4, in <module>
    import win32gui
ModuleNotFoundError: No module named 'win32gui'

**Comment by XCATsus** [comment]
I just fixed it with:
pip install pywin32
